config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  resources :users do
    resources :blogs do
      post "/blog/is_approved", to: "blogs#is_approved"
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  before_save :full_name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
  has_many :comments

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  # app/models/user.rb

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
    end
  end
  def full_name
     self.first_name + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :first_name, :last_name, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
		@blogs = Blog.all
	end

	def new
		@user = User.find(params[:user_id])
		@blog = Blog.new
	end

	def create
		@user = User.find(params[:user_id])
		@blog = @user.blogs.create(blog_params)
		redirect_to root_path
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def show
		#debugger
		@blog = Blog.find(params[:id])
		@comment = Comment.all
	end

	def update
		@user = User.find(params[:user_id])
		@blog = @user.blogs.find(params[:id])
		@blog.update(blog_params)
		redirect_to new_user_blog_path(@user)
	end

	def destroy
		@user = User.find(params[:user_id])
		@blog = @user.blogs.find(params[:id])
		@blog.destroy
		redirect_to new_user_blog_path(@user)
	end

	def is_approved
		@blog = Blog.find(params[:blog_id])
		@blog.update(position: true)
		redirect_to root_path
	end

	private

	def blog_params
		#@blog = Blog.find(params[:id])
		params.require(:blog).permit(:title, :description)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		#debugger
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.create(comment_params)
		@comment.user_id = current_user.id
		@comment.save 
		redirect_to user_blog_path(current_user.id, @blog.id)
	end

	private

	def comment_params
		params.require(:comment).permit(:text)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/blogs/edit.html.erb
<%= form_with scope: :blog, url: user_blogs_path(current_user), method: :post  do |form| %>
<div>
	<%= form.label :title %>
	<%= form.text_field :title %>
</div>
<div>
	<%= form.label :description %>
	<%= form.text_field :description %>
</div>
<div>
	<%= form.submit %>
</div>
<% end %>

app/views/blogs/index.html.erb
<h1>Blogs Here</h1>
<%# debugger %>
<% @blogs.each do |blog| %>
<p>
	<%# debugger %>
	<% if current_user.has_role? :admin %>
	<strong>title</strong>
	<%= blog.title %><br>

	<strong>description</strong>
	<%= blog.description %><br>

	<strong>User_id:</strong>
	<%= blog.user_id%><br>

	<strong>Blog</strong>
	<%= blog.position %><br>
	<%= link_to "View", user_blog_path(blog.user_id, blog.id)%>
	<% if blog.position == false %>
	<%= button_to 'is_approved', user_blog_blog_is_approved_path(blog.user_id,blog.id) %><br>
</p>
<% end %>

<%else%>
<% if blog.position == true %>
	<strong>title</strong>
	<%= blog.title %><br>

	<strong>description</strong>
	<%= blog.description %><br>

	<strong>User_id:</strong>
	<%= blog.user_id%><br>
	<%= link_to "View", user_blog_path(blog.user_id, blog.id)%>
	<% end %>
<% end %>
<% end %>
<%= link_to 'Back', :back %>

app/views/blogs/new.html.erb
<h1>Add New Blog</h1>

<%= form_with scope: :blog, url: user_blogs_path(current_user), method: :post  do |form| %>
<div>
	<%= form.label :title %>
	<%= form.text_field :title %>
</div>
<div>
	<%= form.label :description %>
	<%= form.text_field :description %>
</div>
<div>
	<%= form.submit %>
</div>
<% end %>

app/views/blogs/show.html.erb
<h2>Blogs</h2>

<p>
	<%#debugger%>
	<strong>Blog:</strong>
	<%= @blog.title %>
	<%= @blog.description %>
</p>
<%#= link_to 'edit', edit_user_blog_path(current_user.id,blog.id) %>
<%#=link_to 'Destroy', [blog.user, blog] ,
method: :delete %>

<%= form_with scope: :comment, url: user_blog_comments_path(current_user.id, @blog.id), method: :post  do |form| %>
<div>
	<%= form.label :comment %>
	<%= form.text_field :text %>
</div>
<div>
	<%= form.submit %>
</div>
<% end %>

<h1>Comments</h1>
<% @comment.each do |comment| %>
	<%= comment.text %><br>
<% end %>

app/views/homes/index.html.erb
<h1>Users Index</h1>
<% if user_signed_in?  %>
<% if current_user.has_role? :admin%>
<h2>Hey! Admin Here </h2>
<%else%>
<h2>Hey! User Here</h2>
<% end %>
	<%= current_user.full_name %>
	<%= link_to "Edit", edit_user_registration_path %>
	<%= button_to "Logout", destroy_user_session_path, method: :delete %>
	<%= link_to "Create Blog", new_user_blog_path(current_user)%>
	<%= link_to "Show Blog", user_blogs_path(current_user)%>
<% else %>
	<%= link_to "Sign in" , new_user_session_path %>
	<%= link_to "New User" , new_user_registration_path %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ptask2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>